"""Update : correct table name role_permission

Revision ID: 24d7672be229
Revises: d963ef55f9cc
Create Date: 2025-05-25 09:55:25.086511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d7672be229'
down_revision = 'd963ef55f9cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('role_permission_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('role_permission_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
