"""Update Software to remove Model

Revision ID: 49ab6061cc60
Revises: dd03894b1f8d
Create Date: 2025-06-28 10:03:30.608180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ab6061cc60'
down_revision = 'dd03894b1f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.drop_column('model')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.VARCHAR(length=80), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
