"""update incident Management table

Revision ID: 7b42763e8fbb
Revises: 873d1f00685b
Create Date: 2025-07-12 11:20:09.699236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b42763e8fbb'
down_revision = '873d1f00685b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_management', schema=None) as batch_op:
        batch_op.alter_column('resolved_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_management', schema=None) as batch_op:
        batch_op.alter_column('resolved_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
