"""update incident table to add cve_id

Revision ID: a068cb0e67b4
Revises: c64620d88212
Create Date: 2025-07-17 09:40:01.810083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a068cb0e67b4'
down_revision = 'c64620d88212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_management', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cve_id', sa.String(length=80), nullable=True))
        batch_op.create_foreign_key(None, 'vulnerability', ['cve_id'], ['cve_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_management', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cve_id')

    # ### end Alembic commands ###
