"""update software table to remove unqiue contraints

Revision ID: b9464ca683e7
Revises: a068cb0e67b4
Create Date: 2025-07-31 10:34:05.018745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9464ca683e7'
down_revision = 'a068cb0e67b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vulnerability_fetch_log')
    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.drop_constraint('software_name_key', type_='unique')
        batch_op.drop_constraint('software_vendor_key', type_='unique')
        batch_op.drop_constraint('software_version_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.create_unique_constraint('software_version_key', ['version'])
        batch_op.create_unique_constraint('software_vendor_key', ['vendor'])
        batch_op.create_unique_constraint('software_name_key', ['name'])

    op.create_table('vulnerability_fetch_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='vulnerability_fetch_log_pkey')
    )
    # ### end Alembic commands ###
