"""Update hardware table too allow duplicate values.

Revision ID: dd03894b1f8d
Revises: 87a9653a70f0
Create Date: 2025-06-28 09:51:02.702618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd03894b1f8d'
down_revision = '87a9653a70f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardware', schema=None) as batch_op:
        batch_op.drop_constraint('hardware_manufacturer_key', type_='unique')
        batch_op.drop_constraint('hardware_type_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardware', schema=None) as batch_op:
        batch_op.create_unique_constraint('hardware_type_key', ['type'])
        batch_op.create_unique_constraint('hardware_manufacturer_key', ['manufacturer'])

    # ### end Alembic commands ###
